/home/bingbin/torch/install/bin/luajit: /home/bingbin/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 1 module of nn.Sequential:
...torch/install/share/lua/5.1/nn/VolumetricConvolution.lua:56: 'int64_t' is not callable
stack traceback:
	[C]: in function 'size'
	...torch/install/share/lua/5.1/nn/VolumetricConvolution.lua:56: in function <...torch/install/share/lua/5.1/nn/VolumetricConvolution.lua:48>
	[C]: in function 'xpcall'
	/home/bingbin/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/bingbin/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'func'
	.../bingbin/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	.../bingbin/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
	./objective_3d.lua:78: in function 'opfunc'
	/home/bingbin/torch/install/share/lua/5.1/optim/rmsprop.lua:35: in function 'rmsprop'
	main_3d.lua:143: in function 'graph_training'
	main_3d.lua:261: in main chunk
	[C]: in function 'dofile'
	...gbin/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406620

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/home/bingbin/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/home/bingbin/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'func'
	.../bingbin/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	.../bingbin/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
	./objective_3d.lua:78: in function 'opfunc'
	/home/bingbin/torch/install/share/lua/5.1/optim/rmsprop.lua:35: in function 'rmsprop'
	main_3d.lua:143: in function 'graph_training'
	main_3d.lua:261: in main chunk
	[C]: in function 'dofile'
	...gbin/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406620
